// Generated by LiveScript 1.3.0
var cheerio, request, fs, postmanager, fetchlist, fetchpost, fetchpostAll, fetchNext, dirs, fetchDir;
cheerio = require('cheerio');
request = require('request');
fs = require('fs');
if (!fs.existsSync('raw')) {
  fs.mkdirSync('raw');
}
postmanager = {
  write: function(id, data){
    var p;
    p = this.path(id);
    if (!fs.existsSync("raw/" + p[1])) {
      fs.mkdirSync("raw/" + p[1]);
    }
    return fs.writeFileSync(p[0], data);
  },
  exists: function(id){
    return fs.existsSync(this.path(id)[0]);
  },
  path: function(id){
    var prefix, postfix;
    id = id + "";
    prefix = id.substring(0, 2);
    postfix = id.substring(2);
    return ["raw/" + prefix + "/" + postfix, prefix, postfix];
  }
};
fetchlist = function(dir, page, cb){
  return request({
    url: "https://tw.knowledge.yahoo.com/dir/dir?dir=" + dir + "&sid=396540385&cp=" + page
  }, function(e, r, b){
    var $, questions, qtag, pageinfo, pagerange, pagecount;
    $ = cheerio.load(b);
    questions = [];
    qtag = $('#ykpclv .bd tr');
    qtag.map(function(i, e){
      var link, qid, title, reply;
      if ($(e).find("td").length) {
        link = $(e).find("td.subject a").attr("href");
        qid = /qid=(\d+)$/.exec(link)[1];
        title = $(e).find("td.subject a").text().trim();
        reply = $(e).find("td:last-of-type").text().trim();
        return questions.push({
          title: title,
          qid: qid,
          reply: reply
        });
      }
    });
    pageinfo = $('#ykpclv .bd tr.info th:first-of-type .pagination .page-info').text();
    pagerange = /顯示\s+(\d+)\s+-\s+(\d+)\s+則/.exec(pageinfo);
    pagerange = [parseInt(pagerange[1]), parseInt(pagerange[2])];
    pagecount = /共\s+(\d+)\s+則/.exec(pageinfo);
    pagecount = parseInt(pagecount[1]);
    console.log(questions);
    return cb(questions, pagerange, pagecount);
  });
};
fetchpost = function(item, cb){
  return request({
    url: "https://tw.knowledge.yahoo.com/question/question?qid=" + item.qid
  }, function(e, r, b){
    var $, content;
    $ = cheerio.load(b);
    content = $('#ykpqc_bd .main div').text();
    console.log(item.qid);
    postmanager.write(item.qid, content);
    return cb();
  });
};
fetchpostAll = function(items, cb){
  var item;
  if (items.length === 0) {
    return cb();
  }
  item = items.splice(0, 1)[0];
  return fetchpost(item, function(){
    return setTimeout(function(){
      return fetchpostAll(items, cb);
    }, 1000);
  });
};
fetchNext = function(dir, callback){
  var count, cb2, cb;
  count = 1;
  cb2 = function(){
    count = count + 1;
    return fetchlist(dir, count, cb);
  };
  cb = function(qs, pr, pc){
    console.log(pr[1], pc);
    if (pr[1] >= pc) {
      return setTimeout(callback, 1000);
    }
    return fetchpostAll(qs, cb2);
  };
  return fetchlist(dir, 1, cb);
};
fetchNext();
dirs = ['ask', 'vote', 'solved'];
fetchDir = function(){
  var dir;
  if (!dirs.length) {
    return;
  }
  dir = dirs.splice(0, 1)[0];
  return setTimeout(function(){
    return fetchNext(dir, fetchDir);
  }, 1000);
};